### PR TITLE
Added new provider.

### PR DESCRIPTION
**Pull request by andvenaa**
Added Linkmobility provider.

### CODE REVIEW

**Comment by tzsk** [comment]
@andvenaa Hey... Thanks for the PR. I will look into it and test it. Surely will merge after testing.

**Comment by tzsk** [comment]
@andvenaa Hi... Looks like your PR does not pass StyleCI and Scrutinizer is also lowering the Score of the entire repository. Can you please fix it in your PR?

**Comment by andvenaa** [comment]
@tzsk Now they pass all the test. Was just a crlf to much :)

**Comment by tzsk** [comment]
@andvenaa Merged, Refactored & Released v1.2.0.

Thanks.

**Pull request merged**
